version: '2'
services:
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=192.168.0.80:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=debezium_configs
     - OFFSET_STORAGE_TOPIC=debezium_offsets
     - STATUS_STORAGE_TOPIC=debezium_statuses
     - CONNECT_REQUEST_TIMEOUT_MS=60000
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=true

