USE TPCH
GO

DROP DATABASE IF EXISTS TPCH_SS1 
GO

SELECT * FROM sys.database_files
GO

CREATE DATABASE TPCH_SS1 ON
(NAME = 'TPCH', FILENAME = 'F:\Data\TPCH.mdf.ss1')
--(NAME = 'TPCH_data', FILENAME = 'D:\_mssql\MSSQL14.MSSQLSERVER\MSSQL\DATA\TPCH_data_ndf.ss1')
AS SNAPSHOT OF TPCH
GO
