USE TPCH
GO

--DROP DATABASE TPCH_SS1 
--GO

CREATE DATABASE TPCH_SS1 ON
(NAME = 'TPCH_sys', FILENAME = 'D:\_mssql\MSSQL14.MSSQLSERVER\MSSQL\DATA\TPCH_sys_mdf.ss1'),
(NAME = 'TPCH_data', FILENAME = 'D:\_mssql\MSSQL14.MSSQLSERVER\MSSQL\DATA\TPCH_data_ndf.ss1')
AS SNAPSHOT OF TPCH
GO
