ALTER DATABASE TPCH SET RECOVERY SIMPLE
GO

TRUNCATE TABLE part
TRUNCATE TABLE customer
TRUNCATE TABLE orders
TRUNCATE TABLE partsupp
TRUNCATE TABLE supplier
TRUNCATE TABLE lineitem
TRUNCATE TABLE nation
TRUNCATE TABLE region
GO

BULK INSERT part FROM 'd:\Temp\tpch\part.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT customer FROM 'd:\Temp\tpch\customer.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT orders FROM 'd:\Temp\tpch\orders.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT partsupp FROM 'd:\Temp\tpch\partsupp.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT supplier FROM 'd:\Temp\tpch\supplier.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT lineitem FROM 'd:\Temp\tpch\lineitem.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT nation FROM 'd:\Temp\tpch\nation.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
BULK INSERT region FROM 'd:\Temp\tpch\region.tbl' WITH (TABLOCK, DATAFILETYPE='char', CODEPAGE='raw', FIELDTERMINATOR = '|', BATCHSIZE=10000)
GO

ALTER DATABASE [TPCH] SET RECOVERY FULL
GO

BACKUP DATABASE [TPCH] TO  DISK = N'D:\_mssql\MSSQL14.MSSQLSERVER\MSSQL\Backup\TPCH.bak' 
WITH INIT, NAME = N'TPCH : Full Database Backup', COMPRESSION, STATS = 10